### ISSUE TITLE
Test failing on master branch

### ISSUE THREAD

**Issue by ChristianMurphy** [kmck/rehype-dom#4]
### Subject of the issue

Currently one of the test for rehype-dom is failing on a clean install of the master branch.

### Your environment

*   **OS**: Ubuntu 18.04
*   **Packages**: rehype-dom
*   **Env**:
     - Node: v12.11.1
     - Yarn: 1.19.1
     - Branch: `master`
     - Commit: d9f1575faf71576e413ac5407f44595e077e881e

### Steps to reproduce

```bash
yarn
yarn test
```

### Expected behaviour

Tests pass

### Actual behaviour

```
yarn test
yarn run v1.19.1
$ jest
 PASS  packages/rehype-dom-parse/src/index.test.js
 PASS  packages/rehype-dom-stringify/src/index.test.js
 FAIL  packages/rehype-dom/src/index.test.js
  ● Test suite failed to run

    Cannot find module 'rehype-dom-parse' from 'index.test.js'

       6 | import visit from 'unist-util-visit';
       7 | 
    >  8 | import rehypeDomParse from 'rehype-dom-parse';
         | ^
       9 | import rehypeDomStringify from 'rehype-dom-stringify';
      10 | import rehypeDom from './index';
      11 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:230:17)
      at Object.<anonymous> (packages/rehype-dom/src/index.test.js:8:1)

--------------------------|----------|----------|----------|----------|-------------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
All files                 |      100 |      100 |      100 |      100 |                   |
 rehype-dom-parse/src     |      100 |      100 |      100 |      100 |                   |
  index.js                |      100 |      100 |      100 |      100 |                   |
 rehype-dom-stringify/src |      100 |      100 |      100 |      100 |                   |
  index.js                |      100 |      100 |      100 |      100 |                   |
--------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 2 passed, 3 total
Tests:       8 passed, 8 total
Snapshots:   8 passed, 8 total
Time:        3.32s
Ran all test suites.
error Command failed with exit code 1.

```

**Comment by wooorm** [comment]
Hmm, seems to be that `yarn build` before that works, which is done in the Travis script, I’ll add one `yarn test` to do everything!

**Comment by ChristianMurphy** [comment]
Thanks @wooorm ! :bowing_man:
